name: Test

on:
  pull_request:
    types: [opened, reopened]

  
  workflow_dispatch:


jobs:
  
  Tests:
    
    runs-on: ubuntu-latest

    
    steps:
     
      - uses: actions/checkout@v3
      # Installs packages
      - name: Install packages
        run: npm ci
      # Runs tests
      - name: Run Tests
        run: npm run test
